spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/taskmanagement
          jwk-set-uri: http://localhost:8090/realms/taskmanagement/protocol/openid-connect/certs


  mongodb:
    host: localhost
    port: 27017
    database: userdb
    username: admin
    password: password
    authentication-database: admin

server:
  port: 8085

keycloak:
  realm: taskmanagement
  auth-server-url: http://localhost:8090
  resource: task-management-services
  credentials:
    secret: YOUR_CLIENT_SECRET
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG