spring:
  application:
    name: user-service
  mongodb:
    host: localhost
    port: 27017
    database: userdb
    username: admin
    password: password
    authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/taskmanagement
          jwk-set-uri: http://localhost:8090/realms/taskmanagement/protocol/openid-connect/certs
  task:
    scheduling:
      pool:
        size: 1

server:
  port: 8085




keycloak:
  server-url: http://localhost:8090
  realm: master        # usually "master" for admin login
  username: admin      # Keycloak admin username
  password: admin      # Keycloak admin password
  client-id: admin-cli
  grant-type: password


