spring.application.name=task-service


server.port=8081



# MongoDB Configuration
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=taskdb
spring.mongodb.username=admin
spring.mongodb.password=password
spring.mongodb.authentication-database=admin
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/taskmanagement
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/taskmanagement/protocol/openid-connect/certs
